name: User Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları çek
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli paketleri yükle
      run: pip install -r requirements.txt

    - name: Basit endpoint testi
      run: |
        python app.py &
        sleep 5
        curl http://localhost:5001/users

    - name: Docker image oluştur
      run: docker build -t user-service .
